apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitors-backend-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: visitors-backend-operator
  template:
    metadata:
      labels:
        name: visitors-backend-operator
    spec:
      serviceAccountName: visitors-backend-operator
      containers:
        - name: visitors-backend-operator
          # Replace this with the built image name
          image: image-registry.openshift-image-registry.svc:5000/myprj/visitors-backend-operator
          command:
          - visitors-backend-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "visitors-backend-operator"
