apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitors-frontend-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: visitors-frontend-operator
  template:
    metadata:
      labels:
        name: visitors-frontend-operator
    spec:
      serviceAccountName: visitors-frontend-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          # Replace this with the built image name
          image: "image-registry.openshift-image-registry.svc:5000/myprj/visitors-frontend-operator"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          env:
          - name: ANSIBLE_DEBUG_LOGS
            value: "True"
        - name: operator
          # Replace this with the built image name
          image: "image-registry.openshift-image-registry.svc:5000/myprj/visitors-frontend-operator"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "visitors-frontend-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
