apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: visitorsapps.example.com
spec:
  group: example.com
  names:
    kind: VisitorsApp
    listKind: VisitorsAppList
    plural: visitorsapps
    singular: visitorsapp
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
